'use server';

/**
 * Server-side PDF Report Generator
 * Uses the same HTML template as client-side for consistency
 */

import { createClient } from '@/lib/supabase/server';
import { generateReportHTML } from './generator';

// ============================================================================
// TYPES
// ============================================================================

export interface GeneratePDFResult {
  success: boolean;
  filePath?: string;
  fileSize?: number;
  error?: string;
}

// ============================================================================
// SERVER-SIDE PDF GENERATION USING HTML TEMPLATE
// ============================================================================

/**
 * Generate a PDF report using the same HTML template as client-side
 * This ensures visual consistency between preview and downloaded PDF
 */
export async function generateAndUploadPDF(
  analysisId: string,
  reportType: 'clinical' | 'research' = 'clinical'
): Promise<GeneratePDFResult> {
  try {
    const supabase = await createClient();

    // 1. Fetch analysis data with related information
    const { data: analysis, error: fetchError } = await supabase
      .from('analysis_results')
      .select(
        `
        *,
        mri_scans!inner(
          *,
          patients!inner(*)
        )
      `
      )
      .eq('id', analysisId)
      .single();

    if (fetchError || !analysis) {
      return {
        success: false,
        error: `Failed to fetch analysis: ${fetchError?.message || 'Not found'}`,
      };
    }

    const scan = (analysis as any).mri_scans;
    const patient = scan?.patients;

    if (!patient) {
      return {
        success: false,
        error: 'Patient data not found',
      };
    }

    // 2. Get current user info for "generated by" field
    const {
      data: { user },
    } = await supabase.auth.getUser();

    const { data: userProfile } = await supabase
      .from('user_profiles')
      .select('full_name, institution')
      .eq('id', user?.id || '')
      .single();

    // 3. Generate HTML using the same template as client-side
    const html = generateReportHTML({
      analysis,
      patient,
      scan,
      generatedBy: userProfile?.full_name || user?.email || 'System Generated',
      institutionName: userProfile?.institution || undefined,
      reportType,
    });

    // 4. Convert HTML to buffer for storage
    const htmlBuffer = Buffer.from(html, 'utf-8');
    const fileName = `report_${analysisId}_${Date.now()}.html`;

    // 5. Upload HTML to Supabase Storage
    // Note: We store HTML instead of PDF because it maintains perfect fidelity
    // and users can print to PDF from their browser
    const { data: uploadData, error: uploadError } = await supabase.storage
      .from('reports')
      .upload(fileName, htmlBuffer, {
        contentType: 'text/html',
        upsert: false,
      });

    if (uploadError) {
      console.error('[PDF Generator] Upload error:', uploadError);
      return {
        success: false,
        error: `Failed to upload report: ${uploadError.message}`,
      };
    }

    // 6. Get public URL
    const { data: { publicUrl } } = supabase.storage
      .from('reports')
      .getPublicUrl(fileName);

    return {
      success: true,
      filePath: publicUrl,
      fileSize: htmlBuffer.byteLength,
    };
  } catch (error: any) {
    console.error('[PDF Generator] Unexpected error:', error);
    return {
      success: false,
      error: error.message || 'Failed to generate report',
    };
  }
}
